'use client';

import { FormEvent, useEffect, useState } from 'react';
import LoginForm from '@/components/LoginForm';
import { apiUrl, authHeaders, getStoredToken } from '@/lib/api';
import { Button, Card, EmptyState, Input, PageHeader, StatCard, Table } from '@/components/ui';

type Payment = { id: number; order_id: number; amount: string; payment_method: string; receipt_reference: string | null; created_at: string };
type CreditSummary = { credit_limit: string | null; outstanding_balance: string; available_credit: string | null };
const money = (value: string | number | null) => value === null ? 'Tidak terbatas' : `Rp ${Number(value).toLocaleString('id-ID')}`;

export default function PaymentsPage() {
  const [token, setToken] = useState<string | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [summary, setSummary] = useState<CreditSummary | null>(null); const [orderId, setOrderId] = useState(''); const [amount, setAmount] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const load = async (authToken: string) => { setLoading(true); try { const headers = authHeaders(authToken); const [paymentsResponse, summaryResponse] = await Promise.all([fetch(apiUrl('/payments'), { headers }), fetch(apiUrl('/credit-limit'), { headers })]); if (!paymentsResponse.ok || !summaryResponse.ok) throw new Error('Data pembayaran tidak dapat dimuat.'); setPayments((await paymentsResponse.json()).data); setSummary((await summaryResponse.json()).data); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Data pembayaran tidak dapat dimuat.'); } finally { setLoading(false); } };
  useEffect(() => { const stored = getStoredToken(); setToken(stored); if (stored) load(stored); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!token) return; setError(''); setMessage(''); const response = await fetch(apiUrl('/payments'), { method: 'POST', headers: authHeaders(token), body: JSON.stringify({ order_id: Number(orderId), amount: Number(amount), payment_method: 'cash', idempotency_key: `web-${orderId}-${amount}` }) }); const body = await response.json(); if (!response.ok) { setError(body.message || 'Pembayaran tidak dapat dicatat.'); return; } setMessage(`Pembayaran berhasil dicatat. Referensi: ${body.data.receipt_reference || 'tersedia'}.`); setOrderId(''); setAmount(''); await load(token); };
  if (!token) return <div className="mx-auto max-w-6xl"><PageHeader title="Pembayaran" description="Catat pembayaran dan pantau saldo piutang." /><LoginForm expectedRole="outlet" onLogin={(nextToken) => { setToken(nextToken); load(nextToken); }} /></div>;
  const columns = [{ key: 'order', header: 'Pesanan', render: (payment: Payment) => <span className="font-medium">#{payment.order_id}</span> }, { key: 'method', header: 'Metode', render: (payment: Payment) => <span className="capitalize">{payment.payment_method}</span> }, { key: 'amount', header: 'Jumlah', render: (payment: Payment) => <span className="font-semibold">{money(payment.amount)}</span> }, { key: 'date', header: 'Tanggal', render: (payment: Payment) => new Date(payment.created_at).toLocaleDateString('id-ID') }];
  return <div className="mx-auto max-w-6xl"><PageHeader title="Pembayaran" description="Catat pembayaran dan pantau batas kredit outlet." />{summary && <section className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Batas kredit" value={money(summary.credit_limit)} icon="🎯" /><StatCard label="Piutang berjalan" value={money(summary.outstanding_balance)} icon="⏱️" changeType="down" /><StatCard label="Kredit tersedia" value={money(summary.available_credit)} icon="✅" /></section>}<Card className="mb-6 p-5"><h2 className="mb-4 text-base font-semibold text-gray-900">Catat pembayaran</h2><form onSubmit={submit} className="grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Input required type="number" min="1" label="ID pesanan" value={orderId} onChange={(event) => setOrderId(event.target.value)} placeholder="Contoh: 1024" /><Input required type="number" min="0.01" step="0.01" label="Jumlah pembayaran" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0" /><Button type="submit">Simpan pembayaran</Button></form></Card>{message && <p className="mb-5 rounded-lg border border-success-200 bg-success-50 p-3 text-sm text-success-700">{message}</p>}{error && <p className="mb-5 rounded-lg border border-danger-200 bg-danger-50 p-3 text-sm text-danger-700">{error}</p>}<Card className="overflow-hidden"><div className="border-b border-gray-100 px-5 py-4"><h2 className="font-semibold text-gray-900">Riwayat pembayaran</h2></div>{loading ? <p className="p-8 text-sm text-gray-500">Memuat...</p> : <Table columns={columns} rows={payments} rowKey={(payment) => payment.id} empty={<EmptyState icon={<span>💳</span>} title="Belum ada pembayaran" description="Pembayaran yang Anda catat akan tampil di sini." />} />}</Card></div>;
}
