'use client';

import { useCallback, useEffect, useState } from 'react';
import LoginForm from '@/components/LoginForm';
import { apiUrl, authHeaders, getStoredToken } from '@/lib/api';
import { Badge, Card, EmptyState, PageHeader } from '@/components/ui';

type Measurement = { measured: boolean; note: string };
type DataSufficiency = { sufficient?: boolean; level: string; note: string };
type AIData = { recommendations: Array<{ product_id: number; name: string; price: string; reason: string }>; recommendationMeta: { data_points: number; data_sufficiency: DataSufficiency; measurement: Measurement }; forecast: { predictions: Array<{ period: string; forecast_sales: string; forecast_orders: number }>; data_sufficiency: DataSufficiency; method: string; measurement: Measurement }; segmentation: { segment?: string; confidence?: string; signals?: Record<string, unknown>; segments?: Array<{ outlet_id: number; outlet_name: string; segment: string; confidence: string }> } };

export default function AnalyticsPage() {
  const [token, setToken] = useState<string | null>(null); const [data, setData] = useState<AIData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (authToken: string) => { setLoading(true); setError(null); try { const headers = authHeaders(authToken); const [recommendations, forecast, segmentation] = await Promise.all([fetch(apiUrl('/ai/recommendations'), { headers }), fetch(apiUrl('/ai/forecast?period=weekly&horizon=4'), { headers }), fetch(apiUrl('/ai/segmentation'), { headers })]); const bodies = await Promise.all([recommendations.json(), forecast.json(), segmentation.json()]); const failed = bodies.find((body, index) => ![recommendations, forecast, segmentation][index].ok); if (failed) throw new Error(failed.message || 'Analitik AI tidak dapat dimuat.'); setData({ recommendations: bodies[0].data.recommendations, recommendationMeta: { data_points: bodies[0].data.data_points, data_sufficiency: bodies[0].data.data_sufficiency, measurement: bodies[0].data.measurement }, forecast: bodies[1].data, segmentation: bodies[2].data }); } catch (reason) { setData(null); setError(reason instanceof Error ? reason.message : 'Analitik AI tidak dapat dimuat.'); } finally { setLoading(false); } }, []);
  useEffect(() => { const stored = getStoredToken(); setToken(stored); if (stored) load(stored); }, [load]);
  if (!token) return <div className="mx-auto max-w-6xl"><PageHeader title="Analitik AI" description="Insight yang dapat dijelaskan dari data pesanan Anda." /><div className="mb-5 rounded-lg border border-warning-200 bg-warning-50 p-3 text-sm text-warning-700">Masuk untuk melihat rekomendasi dan prakiraan.</div><LoginForm onLogin={(nextToken) => { setToken(nextToken); load(nextToken); }} /></div>;
  if (loading && !data) return <div className="mx-auto max-w-6xl"><PageHeader title="Analitik AI" description="Insight dari data operasional." /><p className="text-sm text-gray-500">Memuat analitik...</p></div>;
  return <div className="mx-auto max-w-6xl"><PageHeader title="Analitik AI" description="Rekomendasi dan prakiraan deterministik dari data pesanan yang tersedia." />{error && <p role="alert" className="mb-5 rounded-lg border border-danger-200 bg-danger-50 p-3 text-sm text-danger-700">{error}</p>}{data && <div className="grid gap-5 lg:grid-cols-3"><Card className="p-5 lg:col-span-2"><div className="mb-4 flex items-start justify-between"><div><h2 className="font-semibold text-gray-900">Rekomendasi produk</h2><p className="mt-1 text-xs text-gray-500">Berdasarkan {data.recommendationMeta.data_points} pesanan selesai.</p></div><Badge variant="blue">Heuristik</Badge></div>{data.recommendations.length === 0 ? <EmptyState title="Belum ada rekomendasi" description="Rekomendasi akan muncul setelah ada riwayat pembelian." /> : <div className="divide-y divide-gray-100">{data.recommendations.map((item) => <div key={item.product_id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-medium text-gray-900">{item.name}</p><p className="text-xs text-gray-500">{item.reason}</p></div><span className="whitespace-nowrap font-semibold text-primary-700">Rp {Number(item.price).toLocaleString('id-ID')}</span></div>)}</div>}</Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-gray-900">Segmentasi</h2><span className="text-2xl">🎯</span></div>{data.segmentation.segment ? <><p className="text-2xl font-bold text-primary-700">{data.segmentation.segment}</p><p className="mt-1 text-sm text-gray-500">Tingkat keyakinan: {data.segmentation.confidence}</p></> : <ul className="space-y-3">{(data.segmentation.segments || []).slice(0, 10).map((segment) => <li key={segment.outlet_id} className="flex items-center justify-between gap-2 text-sm"><span className="truncate text-gray-700">{segment.outlet_name}</span><Badge variant="gray">{segment.segment}</Badge></li>)}</ul>}</Card><Card className="p-5 lg:col-span-3"><div className="mb-4 flex items-start justify-between"><div><h2 className="font-semibold text-gray-900">Prakiraan 4 minggu</h2><p className="mt-1 text-xs text-gray-500">Metode: {data.forecast.method}. Ini adalah heuristik, bukan probabilitas terkalibrasi.</p></div><span className="text-2xl">📈</span></div>{data.forecast.predictions.length === 0 ? <EmptyState title="Data belum cukup" description="Belum cukup riwayat positif untuk membuat prakiraan." /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.forecast.predictions.map((point) => <div key={point.period} className="rounded-xl bg-gray-50 p-4"><p className="text-sm text-gray-500">{point.period}</p><p className="mt-2 text-lg font-bold text-gray-900">Rp {Number(point.forecast_sales).toLocaleString('id-ID')}</p><p className="mt-1 text-xs text-gray-500">{point.forecast_orders} pesanan</p></div>)}</div>}</Card></div>}</div>;
}
