'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import LoginForm from '@/components/LoginForm';
import { OutletPerformanceChart, SalesTrendChart, OutletPoint, TrendPoint } from '@/components/Charts';
import { apiUrl, authHeaders, getStoredToken } from '@/lib/api';
import { Button, Card, Input, PageHeader, Select, StatCard } from '@/components/ui';

type Group = 'daily' | 'weekly' | 'monthly';
type Metrics = { orders_total: number; sales_total: string; outlets_total: number; products_total: number; payments_total: string; outstanding_total: string };
type DashboardData = { metrics: Metrics; sales_trends: TrendPoint[]; outlet_performance: OutletPoint[] };
function defaultStartDate(): string { const date = new Date(); date.setDate(date.getDate() - 29); return date.toISOString().slice(0, 10); }
function today(): string { return new Date().toISOString().slice(0, 10); }
const rupiah = (value: string | number) => `Rp ${Number(value).toLocaleString('id-ID')}`;

export default function DashboardPage() {
  const [token, setToken] = useState<string | null>(null); const [ready, setReady] = useState(false); const [startDate, setStartDate] = useState(defaultStartDate); const [endDate, setEndDate] = useState(today); const [group, setGroup] = useState<Group>('daily'); const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadDashboard = useCallback(async (authToken: string) => { setLoading(true); setError(null); try { const query = new URLSearchParams({ start_date: startDate, end_date: endDate, group }); const response = await fetch(`${apiUrl('/analytics/dashboard')}?${query}`, { headers: authHeaders(authToken) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || 'Data dasbor tidak dapat dimuat.'); setDashboard(body.data); } catch (reason) { setDashboard(null); setError(reason instanceof Error ? reason.message : 'Data dasbor tidak dapat dimuat.'); } finally { setLoading(false); } }, [endDate, group, startDate]);
  useEffect(() => { const storedToken = getStoredToken(); setToken(storedToken); setReady(true); }, []);
  useEffect(() => { if (token) loadDashboard(token); }, [loadDashboard, token]);
  const hasData = useMemo(() => dashboard && (dashboard.metrics.orders_total > 0 || dashboard.metrics.sales_total !== '0.00' || dashboard.metrics.payments_total !== '0.00'), [dashboard]);
  if (!ready) return <p className="text-sm text-gray-500">Memuat...</p>;
  if (!token) return <div className="mx-auto max-w-6xl"><PageHeader title="Dasbor eksekutif" description="Ringkasan performa bisnis dan distribusi." /><div className="mb-5 rounded-lg border border-warning-200 bg-warning-50 p-3 text-sm text-warning-700">Masuk sebagai administrator untuk melihat analitik bisnis.</div><LoginForm expectedRole="admin" onLogin={(nextToken) => setToken(nextToken)} /></div>;
  return <div className="mx-auto max-w-6xl"><PageHeader title="Dasbor eksekutif" description="Ringkasan performa penjualan, pembayaran, produk, dan outlet." /><Card className="mb-6 p-4"><form className="grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={(event) => { event.preventDefault(); if (token) loadDashboard(token); }}><Input label="Dari tanggal" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /><Input label="Sampai tanggal" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /><Select label="Kelompok tren" value={group} onChange={(event) => setGroup(event.target.value as Group)}><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></Select><Button type="submit" disabled={loading}>{loading ? 'Memuat...' : 'Terapkan filter'}</Button></form></Card>{error && <p role="alert" className="mb-6 rounded-lg border border-danger-200 bg-danger-50 p-3 text-sm text-danger-700">{error}</p>}{loading && !dashboard && <p className="text-sm text-gray-500">Memuat data analitik...</p>}{!loading && dashboard && !hasData && <Card className="mb-6 p-6 text-sm text-gray-500">Belum ada data pada rentang tanggal ini.</Card>}{dashboard && <><section aria-label="Metrik utama" className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><StatCard label="Total penjualan" value={rupiah(dashboard.metrics.sales_total)} icon="💰" /><StatCard label="Total pesanan" value={dashboard.metrics.orders_total.toLocaleString('id-ID')} icon="🛒" /><StatCard label="Outlet aktif" value={dashboard.metrics.outlets_total.toLocaleString('id-ID')} icon="🏪" /><StatCard label="Produk aktif" value={dashboard.metrics.products_total.toLocaleString('id-ID')} icon="📦" /><StatCard label="Pembayaran selesai" value={rupiah(dashboard.metrics.payments_total)} icon="💳" /><StatCard label="Piutang" value={rupiah(dashboard.metrics.outstanding_total)} icon="⏱️" changeType="down" /></section><section className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="mb-4 text-base font-semibold text-gray-900">Tren penjualan</h2><SalesTrendChart points={dashboard.sales_trends} /></Card><Card className="p-5"><h2 className="mb-4 text-base font-semibold text-gray-900">Performa outlet</h2><OutletPerformanceChart outlets={dashboard.outlet_performance} /></Card></section></>}</div>;
}
